name: flutter_weather_bg_example
description: Demonstrates how to use the flutter_weather_bg plugin.

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_weather_bg_null_safety:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
